/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionConfirmation: typeof import('./src/components/ActionConfirmation.vue')['default']
    DeleteConfirmation: typeof import('./src/components/DeleteConfirmation.vue')['default']
    EditEquipmentForm: typeof import('./src/components/EquipmentForms/EditEquipmentForm.vue')['default']
    EditEventForm: typeof import('./src/components/EventForms/EditEventForm.vue')['default']
    Equipments: typeof import('./src/components/Equipments.vue')['default']
    EventForm: typeof import('./src/components/EventForm.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewEventForm: typeof import('./src/components/EventForms/NewEventForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
